<?php

namespace WebmastersAfrica\PressBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepliedMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepliedMessageRepository extends EntityRepository
{
}
