managebanners:
    pattern:  /
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:index" }

managebanners_show:
    pattern:  /{id}/show
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:show" }

managebanners_new:
    pattern:  /new
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:new" }

managebanners_create:
    pattern:  /create
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:create" }
    requirements: { _method: post }

managebanners_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:edit" }

managebanners_update:
    pattern:  /{id}/update
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:update" }
    requirements: { _method: post|put }

managebanners_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "WebmastersAfricaPressBundle:Banner:delete" }