WebmastersAfrica\TaskBundle\Entity\User:
    properties:
        taskDescription:
            - NotBlank: ~
        taskStartDate:
            - NotBlank: ~
        taskEndDate:
            - NotBlank: ~
        License:
            - NotBlank: ~