worker_processes  1;
daemon off;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;

  server {
    include listen.conf;
    include root.conf;
    charset utf-8;

    index index.html index.htm index.php;

    error_log  /dev/stderr info;
    access_log /dev/stdout;

    client_max_body_size 5m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /backend.php {
        try_files $uri $uri/ /backend.php?$query_string;
    }

    location /uploads/ {
        include uploads_dir.conf;
    }

    location /asset_uplds/ {
        include uploads_dir.conf;
    }

    location /assets_unified/ {
        try_files $uri $uri/ $uri.html =404;
    }

    #error_page  404              /index.php;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # pass the PHP scripts to FastCGI server listening on /var/run/php5-fpm-permitflow-ntsa.sock
    #
    location ~ \.php {
        include /etc/nginx/fastcgi_params;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_pass_sock;
        #fastcgi_pass unix:/var/run/php5-fpm-permitflow-ntsa.sock;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # pass status requests to php-fpm
    location ~ /(status|ping) {
    	#fastcgi_pass unix:/var/run/php5-fpm.sock;
      include fastcgi_pass_sock;
    	include /etc/nginx/fastcgi_params;
    	fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny  all;
    }

  }
}
