parameters:
#    webmasters_africa_message.example.class: WebmastersAfrica\MessageBundle\Example

services:
#    webmasters_africa_message.example:
#        class: %webmasters_africa_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
