<?php

namespace OTB\Bundle\NoticeAndCommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbusiveTermsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbusiveTermsRepository extends EntityRepository
{
    public function findOnyUniqueOnes()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $result = $this->_em->createQueryBuilder()
            ->addSelect('bl.terms')
            ->addSelect('bl.id')
            ->from('NoticeCommentBundle:AbusiveTerms', 'bl')
            ->groupBy('bl.terms')
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
        return $result;
    }
}
