<?php

namespace OTB\Bundle\NoticeAndCommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getReplies($comment_id, $limit)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('c.parent', ':comment'),
            $expr->isNull('c.deletedAt')
        );

        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('comment', $comment_id)
            ->orderBy('c.id', 'desc')
            ->setFirstResult(0)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function getCommentsToCheckForAbusiveWords()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('c.checkAbusive', 0)
        );

        return $this->createQueryBuilder('c')
            ->where($andX)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getRepliesCount($comment_id)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('c.parent', ':comment'),
            $expr->isNull('c.deletedAt')
        );

        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('comment', $comment_id)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getMatchAbusiveWords($comment)
    {
        $comment = "%" . $comment . "%";
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->like('c.comment', ":comment"),
            $expr->isNull('c.deletedAt')
        );

        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('comment', $comment)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getRegulationComments($regulation)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('r.id', ':regulation')
        );
        return $this->createQueryBuilder('c')
            ->leftJoin('c.regulation', 'r')
            ->where($andX)
            ->setParameter('regulation', $regulation)
            ->addOrderBy('c.upvoteCount', 'DESC')
            ->addOrderBy('c.createAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getActiveComments()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->isNull('c.parent'),
            $expr->isNull('c.deletedAt'),
            $expr->eq('c.isAbusive', ':abusive')
        );
        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('abusive', 0)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getAbusiveComments()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->isNull('c.deletedAt'),
            $expr->eq('c.isAbusive', ':abusive')
        );
        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('abusive', 1)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }

    public function getUnpublishedComments($regulation_id)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('c.regulation', ':regulation'),
            $expr->isNull('c.parent')
        );
        $orx = $expr->orX(
            $expr->eq('c.hidden', 1),
            $expr->eq('c.publish', 0)
        );
        $andX->add($orx);
        return $this->createQueryBuilder('c')
            ->where($andX)
            ->setParameter('regulation', $regulation_id)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }
}
