<?php

namespace OTB\Bundle\NoticeAndCommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForwardPlansRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForwardPlansRepository extends EntityRepository
{
    public function listAllForwardsPlansByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('fc.deleted', 0),
            $expr->eq('fc.published', 1),
            $expr->in('fc.agency', $agency)
        );

        return $this->createQueryBuilder('fp')
            ->leftJoin('fp.forwardPlanCategory', 'fc')
            ->leftJoin('fc.agency', 'a')
            ->where($andX)
            ->orderBy('fp.id', 'DESC')
            ->getQuery()
            ->execute();
    }
}
