<?php

namespace OTB\Bundle\NoticeAndCommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForwardPlansRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForwardPlanMainCategoryRepository extends EntityRepository
{
    public function listAllMainForwardPlansInMyAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->in('f.agency', ":agency")
        );



        return $this->createQueryBuilder('f')
                ->where($andX)
                ->orderBy('f.id', 'DESC')
                ->setParameter(':agency', $agency)
                ->getQuery()
                ->execute();
    }
}
