<?php

namespace OTB\Bundle\NoticeAndCommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegulationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegulationRepository extends EntityRepository
{
    public function findAll()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
                ->where($andX)
                ->orderBy('bl.id', 'DESC')
                ->getQuery()
                ->execute();
    }

    public function getAllRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();

        return $this->createQueryBuilder('bl')
                ->orderBy('bl.id', 'DESC')
                ->getQuery()
                ->execute();
    }

    public function findRegulationsByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->in('a.id', ":agency")
        );
        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->leftJoin('bl.agency', 'a')
            ->setParameter('agency', $agency)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findOpenRegulationsByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.consultationStage', 1),
            $expr->eq('bl.isPublic', 1),
            $expr->eq('bl.published', 1),
            $expr->in('a.id', ":agency")
        );
        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->leftJoin('bl.agency', 'a')
            ->setParameter('agency', $agency)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findCompletedRegulationsByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->eq('bl.consultationStage', 2),
            $expr->in('a.id', ":agency"),
            $expr->eq('bl.isPublic', 1)
        );
        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->leftJoin('bl.agency', 'a')
            ->setParameter('agency', $agency)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
    public function findInternalRegulationsByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 0)
        );
        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->leftJoin('bl.agency', 'a')
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findUnpublishedRegulationsByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.published', 0),
            $expr->in('a.id', ":agency")
        );
        return $this->createQueryBuilder('bl')
            ->leftJoin('bl.agency', 'a')
            ->where($andX)
            ->setParameter('agency', $agency)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getRegulationsForLandingPage()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1),
            $expr->eq('bl.consultationStage', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(4)
            ->getQuery()
            ->execute();
    }

    public function getListOfActiveRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.consultationStage', 1),
            $expr->eq('bl.checkClosing', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
    public function getListOfFrontendRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function searchByDetails($search_term)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('r.deleted', ":deleted"),
            $expr->eq('r.published', ":published"),
            $expr->eq('r.isPublic', ":isPublic")
        );
        $orX = $expr->orX(
            $expr->like('r.title', ':title'),
            $expr->like('r.description', ':description'),
            $expr->like('r.keywords', ':keywords'),
            $expr->like('r.closingDate', ':closingDate'),
            $expr->like('a.name', ':agency'),
            $expr->like('i.name', ':industry'),
            $expr->like('r.tags', ':tags'),
            $expr->like('r.specificInstructions', ':specificInstructions')
        );

        $params = [];
        $params = [
            'published' => 1,
            'isPublic' => 1,
            'deleted' => 0,
        ];
        $params['title'] = "%" . $search_term . "%";
        $params['description'] = "%". $search_term."%";
        $params['closingDate'] = "%". $search_term."%";
        $params['agency'] = "%". $search_term."%";
        $params['tags'] = "%". $search_term."%";
        $params['keywords'] = "%". $search_term."%";
        $params['specificInstructions'] = "%". $search_term."%";
        $params['industry'] = "%". $search_term."%";
        $andX->add($orX);
        $qb = $this->createQueryBuilder('r')
                ->leftJoin('r.industry', 'i')
                ->leftJoin('r.agency', 'a')
                ->where($andX)
                ->orderBy('r.title', 'ASC')
                ->setParameters($params)
                ->getQuery()->getResult();
        return $qb;
    }

    public function getPublishedRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $orX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->eq('bl.deleted', 0)
        );

        return $this->createQueryBuilder('bl')
            ->where($orX)
            ->getQuery()
            ->getResult();
    }
    public function getInternalConsultations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $orX = $expr->andX(
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 0)
        );

        return $this->createQueryBuilder('bl')
            ->where($orX)
            ->getQuery()
            ->getResult();
    }
    public function getAllUnpublishedRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $orX = $expr->orX(
            $expr->eq('bl.published', 0),
            $expr->eq('bl.deleted', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($orX)
            ->getQuery()
            ->getResult();
    }

    public function getAllPublishedAndUnpublishedRegulations($published = true)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0)
        );

        if ($published) {
            $andX->add(
                $expr->eq('bl.published', 1)
            );
        } else {
            $andX->add(
                $expr->eq('bl.published', 0)
            );
        }

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->getQuery()
            ->getResult();
    }



    public function getAllRegulationsOpenForConsultation()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.consultationStage', 1),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->execute();
    }

    public function getAllRegulationsClosedForConsultation()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.consultationStage', 2),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->execute();
    }
    public function getAllRegulationsClosedForConsultationSideMenu()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.consultationStage', 2),
            $expr->eq('bl.deleted', 0),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->setMaxResults(3)
            ->getQuery()
            ->execute();
    }

    public function getCheckForClosingRegulations()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->eq('bl.consultationStage', 1),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->setMaxResults(30)
            ->getQuery()
            ->getResult();
    }
    /**
     * Get Regulations with Comments Greater than Ten order by Publish Date
     *
     * @return EntityRepository
     */
    public function getRegulationsWithCommentsGreaterThenTen()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        return $this->_em->createQueryBuilder()
            ->addSelect('r.id')
            ->addSelect('COUNT(c.comment) as comment_count')
            ->from('NoticeCommentBundle:Regulation', 'r')
            ->leftJoin('r.comments', 'c')
            ->where(
                $expr->andX(
                    $expr->eq('r.deleted', '0'),
                    $expr->eq('r.consultationStage', 1),
                    $expr->eq('r.published', 1),
                    $expr->eq('r.isPublic', 1)
                )
            )
            ->groupBy('r.id')
            ->having($expr->gte('comment_count', '10'))
            ->setMaxResults(1)
            ->orderBy('comment_count', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Count Comments for regulations per agreement agreement
     *
     * @return EntityRepository
     */
    public function getCategorizedCommentsPerRegulation(int $regulation_id)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        return $this->_em->createQueryBuilder()
            ->addSelect('c.id')
            ->addSelect('c.position')
            ->from('NoticeCommentBundle:Regulation', 'r')
            ->leftJoin('r.comments', 'c')
            ->where(
                $expr->andX(
                    $expr->eq('r.deleted', '0'),
                    $expr->eq('c.regulation', ':regulation'),
                    $expr->eq('r.published', 1),
                    $expr->eq('r.isPublic', 1)
                )
            )
            ->setParameter('regulation', $regulation_id)
            ->orderBy('r.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Get regulations with the largest number of likes
     *
     * @return Entity Respostory
     */
    public function getRegulationsWithLargestExpression()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        return $this->_em->createQueryBuilder()
            ->addSelect('v.id')
            ->addSelect('SUM(l.id) AS likes_count')
            ->from('NoticeCommentBundle:Comment', 'u')
            ->leftJoin('u.regulation', 'v')
            ->leftJoin('u.likes', 'l')
            ->where(
                $expr->andX(
                    $expr->eq('v.deleted', 0),
                    $expr->eq('v.checkClosing', 1),
                    $expr->eq('v.published', 1),
                    $expr->eq('v.isPublic', 1),
                    $expr->isNull('u.parent')
                )
            )->groupBy('v.id')
            ->orderBy('likes_count', 'DESC')
            ->having('sum(l.id) > 10')
            ->getQuery()
            ->setMaxResults(1)
            ->getResult();
    }

    /**
     * Get comment with the largest number of likes
     *
     * @return Entity Respostory
     */
    public function getCommentWithLargestExpression()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        return $this->_em->createQueryBuilder()
            ->addSelect('u.id')
            ->addSelect('SUM(l.id) AS likes_count')
            ->from('NoticeCommentBundle:Comment', 'u')
            ->leftJoin('u.regulation', 'v')
            ->leftJoin('u.likes', 'l')
            ->where(
                $expr->andX(
                    $expr->eq('v.deleted', 0),
                    $expr->eq('v.checkClosing', 1),
                    $expr->eq('v.published', 1),
                    $expr->eq('v.isPublic', 1)
                )
            )->groupBy('v.id')
            ->orderBy('likes_count', 'DESC')
            ->having('sum(l.id) > 10')
            ->getQuery()
            ->setMaxResults(1)
            ->getResult();
    }

    /**
     * Get Regulations with Comments Greater than Ten order by Publish Date
     *
     * @return EntityRepository
     */
    public function getRegulationsWithLargeNumberOfComments()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        return $this->_em->createQueryBuilder()
            ->addSelect('r.id')
            ->addSelect('COUNT(c.comment) as comment_count')
            ->from('NoticeCommentBundle:Regulation', 'r')
            ->leftJoin('r.comments', 'c')
            ->where(
                $expr->andX(
                    $expr->eq('r.deleted', '0'),
                    $expr->eq('r.checkClosing', 1),
                    $expr->eq('r.published', 1),
                    $expr->eq('r.isPublic', 1),
                    $expr->isNUll('c.parent')
                )
            )
            ->groupBy('r.id')
            ->orderBy('comment_count', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();
    }

    public function getRegulationsCountPerIndustry()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i.id, count(r.id) as regulation_count, i.name
                FROM NoticeCommentBundle:Regulation r INNER JOIN
                WebmastersAfricaLicenseBundle:BusinessIndustry i
                WITH r.industry = i.id WHERE i.deleted = 0 AND r.published = 1 AND r.isPublic = 0
                GROUP BY r.id'
            )->getResult();
    }

    /**
     * Get the list of all keywords
     *
     * @return EntityRepository
     */
    public function getListOfAllKeywords()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.keywords
                FROM NoticeCommentBundle:Regulation r
                WHERE r.deleted = 0 and r.published = 1 and r.isPublic = 0'
            )->getResult();
    }

    public function searchByIndustryKeyword($industry, $keyword)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('i.name', ":industry"),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );
        $orX = $expr->orX(
            $expr->like('bl.title', ':name'),
            $expr->like('bl.description', ':description'),
            $expr->like('i.name', ':industry_name'),
            $expr->like('bl.keywords', ':keywords'),
            $expr->like('a.name', ':agency')
        );
        $andX->add($orX);
        $params['industry'] = $industry;
        $params['industry_name'] = "%" .$keyword. "%";
        $params['agency'] = "%" .$keyword. "%";
        $params['keywords'] = "%" .$keyword. "%";
        $params['name'] = "%" .$keyword. "%";
        $params['description'] = "%" .$keyword. "%";
        return $this->createQueryBuilder('bl')
            ->leftJoin('bl.agency', 'a')
            ->leftJoin('bl.industry', 'i')
            ->where($andX)
            ->setParameters($params)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function searchByAgencyIndustry($agency, $industry)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('a.title', ":agency"),
            $expr->like('i.name', ":industry"),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        $params['agency'] = "%". $agency . "%";
        $params['industry'] = "%". $industry . "%";
        return $this->createQueryBuilder('bl')
            ->leftJoin('bl.agency', 'a')
            ->leftJoin('bl.industry', 'i')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->setParameters($params)
            ->execute();
    }

    public function searchByAgencyIndustryKeyword($agency, $industry, $keyword)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('a.name', ":agency"),
            $expr->like('i.name', ":industry"),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );
        $orX = $expr->orX(
            $expr->like('bl.title', ':title'),
            $expr->like('bl.description', ':description'),
            $expr->like('bl.keywords', ':keywords'),
            $expr->like('a.name', ':agency_name'),
            $expr->like('i.name', ':industry_name'),
            $expr->like('bl.tags', ':tags'),
            $expr->like('bl.specificInstructions', ':specificInstructions')
        );
        $andX->add($orX);
        $params['agency'] = "%". $agency . "%";
        $params['industry'] = "%". $industry . "%";
        $params['title'] = "%". $keyword . "%";
        $params['keywords'] = "%". $keyword . "%";
        $params['description'] = "%". $keyword . "%";
        $params['agency_name'] = "%". $keyword . "%";
        $params['industry_name'] = "%". $keyword . "%";
        $params['tags'] = "%". $keyword . "%";
        $params['specificInstructions'] = "%". $keyword . "%";

        return $this->createQueryBuilder('bl')
            ->leftJoin('bl.agency', 'a')
            ->leftJoin('bl.industry', 'i')
            ->where($andX)
            ->setParameters($params)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function searchByIndustry($industry)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('r.deleted', 0),
            $expr->like('i.name', ":industry"),
            $expr->eq('i.deleted', 0),
            $expr->eq('r.published', 1),
            $expr->eq('r.isPublic', 1)
        );

        return $this->createQueryBuilder('r')
            ->leftJoin('r.industry', 'i')
            ->where($andX)
            ->orderBy('r.id', 'DESC')
            ->setParameter('industry', "%" . $industry. "%")
            ->getQuery()
            ->getResult();
    }

    public function searchByAgencyKeyword($agency, $keyword)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('a.name', ":agency"),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );
        $orX = $expr->orX(
            $expr->like('bl.title', ':name'),
            $expr->like('bl.description', ':description'),
            $expr->like('bl.keywords', ':keywords'),
            $expr->like('a.name', ':agency_name'),
            $expr->like('i.name', ':industry')
        );
        $andX->add($orX);
        $params['agency'] = "%" . $agency . "%";
        $params['description'] = "%" . $keyword . "%";
        $params['keywords'] = "%" . $keyword . "%";
        $params['agency_name'] = "%" . $keyword . "%";
        $params['name'] = "%" . $keyword . "%";
        $params['industry'] = "%" . $keyword . "%";


        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->leftJoin('bl.agency', 'a')
            ->leftJoin('bl.industry', 'i')
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->setParameters($params)
            ->execute();
    }

    public function searchByKeyword($keyword)
    {

        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('bl.keywords', ':keyword'),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );
        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->setParameter('keyword', '%' . $keyword . '%')
            ->execute();
    }

    public function searchByAgency($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();

        $andX = $expr->andX(
            $expr->eq('bl.deleted', 0),
            $expr->like('a.title', ':agency'),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );
        return $this->createQueryBuilder('bl')
            ->leftJoin('bl.agency', 'a')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->getQuery()
            ->setParameter('agency', "%" . $agency . "%")
            ->execute();
    }

    public function getDashLicense($agency)
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $andX = $expr->andX(
            $expr->eq('bl.deleted', ':deleted'),
            $expr->in('bl.agency', ':agency'),
            $expr->eq('bl.checkClosing', 1),
            $expr->eq('bl.published', 1),
            $expr->eq('bl.isPublic', 1)
        );

        return $this->createQueryBuilder('bl')
            ->where($andX)
            ->orderBy('bl.id', 'DESC')
            ->setParameters(
                [
                    'deleted' => 0,
                    'agency' => $agency
                ]
            )
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();
    }

    public function getNumberOfLicensesPerAgency()
    {
        $expr = $this->_em->createQueryBuilder()->expr();
        $result = $this->_em->createQueryBuilder()
            ->addSelect('ba.title')
            ->addSelect('COUNT(bl.id) as number_of_licenses')
            ->from('NoticeCommentBundle:Regulation', 'bl')
            ->innerJoin('bl.agency', 'ba')
            ->where(
                $expr->andX(
                    $expr->eq('bl.deleted', "0"),
                    $expr->eq('ba.deleted', "0"),
                    $expr->eq('bl.published', '1'),
                    $expr->eq('bl.isPublic', 1)
                )
            )
            ->groupBy('ba.title')
            ->orderBy('number_of_licenses', 'DESC')
            ->getQuery()
            ->getResult();
        return $result;
    }
}
